### ISSUE TITLE
How to create own policy

### ISSUE THREAD

**Issue by ajaylamoria** [StyraInc/opa-java#51]
opa-sdk

I wanted to understand how do i create a OPA policy using OpaAPiClient.

**Comment by charlesdaniels** [comment]
Hi, I think you and I discussed this in the community Slack and got it figured out then.

In the time since then, I have taken some of the info I put together for that Slack conversation and turned it into proper publicly accessible docs. 

You can find those docs [here](https://docs.styra.com/sdk/java/examples) and [here](https://docs.styra.com/sdk/java/tutorials/hello-world).

I'll also leave here as a breadcrumb for any future Googlers - Ajay was also interested in how exactly one could go about hitching up OPA policies for use in unit testing scenarios. My suggestion for folks with this need is to use [testcontainers](https://java.testcontainers.org/). This is how the opa-java test suite is implemented. The current version of the test suite has some extra complexity in terms of how testcontainers are used to support testing API  prefixing. For a more straightforward example, [this slightly older version of the tests](https://github.com/StyraInc/opa-java/blob/0ef5d044c7c68ea0273753d54e4e8c7dcd98887d/src/test/java/com/styra/opa/OPATest.java) may be more illustrative.

Going to close this out, feel free to reach out if you have further questions.
